"""<your message>

Revision ID: 0764f3bf13f0
Revises: 6e3e74b490e1
Create Date: 2023-05-31 23:04:49.920973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0764f3bf13f0'
down_revision = '6e3e74b490e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toppings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toppings', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
