"""<your message>

Revision ID: 4a857ae77b55
Revises: 8cbd98118f9b
Create Date: 2023-05-31 23:07:20.682917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a857ae77b55'
down_revision = '8cbd98118f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_payment_id_payments'), 'payments', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_payment_id_payments'), type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
