"""Initial migration.

Revision ID: 4e5ba58397f4
Revises: 278205563ebb
Create Date: 2023-05-23 17:39:28.928257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5ba58397f4'
down_revision = '278205563ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('set_toppings', sa.String(), nullable=True),
    sa.Column('custom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sides')
    # ### end Alembic commands ###
