"""Initial migration.

Revision ID: 564d082b8c01
Revises: 4e5ba58397f4
Create Date: 2023-05-23 17:51:12.335055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564d082b8c01'
down_revision = '4e5ba58397f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewithtoppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('side_id', sa.Integer(), nullable=False),
    sa.Column('topping_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['side_id'], ['sides.id'], name=op.f('fk_sidewithtoppings_side_id_sides')),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], name=op.f('fk_sidewithtoppings_topping_id_toppings')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sidewithtoppings')
    # ### end Alembic commands ###
