"""<your message>

Revision ID: 6e3e74b490e1
Revises: 
Create Date: 2023-05-31 22:13:32.156981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3e74b490e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('alcoholic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('set_toppings', sa.String(), nullable=True),
    sa.Column('custom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('set_toppings', sa.String(), nullable=True),
    sa.Column('custom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticketnumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_number_id'], ['ticketnumbers.id'], name=op.f('fk_orders_ticket_number_id_ticketnumbers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productwithtoppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('topping_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_productwithtoppings_product_id_products')),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], name=op.f('fk_productwithtoppings_topping_id_toppings')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sidewithtoppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('side_id', sa.Integer(), nullable=False),
    sa.Column('topping_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['side_id'], ['sides.id'], name=op.f('fk_sidewithtoppings_side_id_sides')),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], name=op.f('fk_sidewithtoppings_topping_id_toppings')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_with_topping_id', sa.Integer(), nullable=False),
    sa.Column('side_with_topping_id', sa.Integer(), nullable=False),
    sa.Column('mealprice', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_with_topping_id'], ['productwithtoppings.id'], name=op.f('fk_order_items_product_with_topping_id_productwithtoppings')),
    sa.ForeignKeyConstraint(['side_with_topping_id'], ['sidewithtoppings.id'], name=op.f('fk_order_items_side_with_topping_id_sidewithtoppings')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('long_card_number', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('sidewithtoppings')
    op.drop_table('productwithtoppings')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('toppings')
    op.drop_table('ticketnumbers')
    op.drop_table('sides')
    op.drop_table('products')
    op.drop_table('drinks')
    # ### end Alembic commands ###
