"""Initial migration.

Revision ID: 981648d2d73f
Revises: 564d082b8c01
Create Date: 2023-05-23 18:11:22.145465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981648d2d73f'
down_revision = '564d082b8c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('alcoholic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    # ### end Alembic commands ###
